### PR TITLE
Fix oracle-related issues

### LINKED ISSUE #4: OracleNotificationInput flagged as non-simple I/O type (false positive for oracle callbacks)
## Description

contract-verify v1.0.5 rejects `OracleNotificationInput<T>` when used as an `_input` typedef for oracle callback procedures registered via `REGISTER_USER_PROCEDURE_NOTIFICATION`.

**Error:**
```
[ ERROR ] OnAIVerifyReply_input is not allowed as input/output type.
The input and output structs of contract user procedures and functions
may only use integer and boolean types (such as uint64, sint8, bit)
as well as id, Array, and BitArray, and struct types containing only allowed types.
```

**Contract code:**
```cpp
typedef OracleNotificationInput<AIVerifyOracle> OnAIVerifyReply_input;
typedef NoData OnAIVerifyReply_output;

REGISTER_USER_PROCEDURE_NOTIFICATION(OnAIVerifyReply);
```

## Why this is a false positive

`QUtil.h` in `qubic/core` uses the **identical pattern** for oracle price notifications:
```cpp
typedef OracleNotificationInput<OI::Price> NotifyPriceOracleReply_input;
typedef NoData NotifyPriceOracleReply_output;
```

QUtil is excluded from contract-verify in the upstream CI workflow (`! -name "*QUtil*"`), so this never surfaces. However, **any new contract** that implements oracle integration will hit this error.

`OracleNotificationInput<T>` is a QPI-provided template from `qpi.h` — it is the standard mechanism for receiving oracle callbacks. It should be treated as an allowed I/O type.

## Suggestion

Whitelist `OracleNotificationInput<T>` as an allowed input type specifically for procedures registered with `REGISTER_USER_PROCEDURE_NOTIFICATION`. These are private oracle callback procedures, not user-facing procedures, and their I/O types are dictated by the QPI framework.

## Environment

- contract-verify: v1.0.5
- qubic/core: develop branch (ba09666, 2026-03-31)
- Contract: QAGENT (AI agent marketplace with AIVerify oracle interface)

### PR DESCRIPTION
**Pull request by Franziska-Mueller**
This PR fixes oracle-related issues with the contract verification.

Specifically, the scope resolution check has been significantly enhanced and a workaround for a parser bug in regards to macro names has been added. The contract verify tool now passes on QUtil again.

### CODE REVIEW

**Comment by Franziska-Mueller** [comment]
@philippwerner sorry for the mess with the deleted dependencies. The only interesting changes are in commit https://github.com/Franziska-Mueller/qubic-contract-verify/pull/5/changes/5392c9a6168fd38799d83f5d9f1ee0adde3d039c and https://github.com/Franziska-Mueller/qubic-contract-verify/pull/5/changes/d6cc6d412758f96010f6d6df8cfe7bcffbda2916

**Comment by RideMatch1** [comment]
This fix addresses exactly the issue we hit with the QAGENT contract ([qubic/core#814](https://github.com/qubic/core/pull/814)).

Our contract uses `OracleNotificationInput<AIVerifyOracle>` for the AIVerify oracle callback, which is the standard QPI pattern for oracle notifications. The current verifier (v1.0.5) rejects it as an invalid I/O type.

As a temporary workaround we switched from `typedef` to a `using` alias, which the current verifier doesn't flag. Both are semantically identical in C++, so this confirms the check was matching on syntax rather than semantics.

Happy to test the updated verifier against our contract once this lands — QAGENT is probably the most thorough real-world test case for oracle integration right now (one-time query with AIVerify, notification callback, full dispute resolution flow).

File: src/lib/check_names_and_types.cpp [hunk 1]
```diff
@@ -127,6 +127,14 @@ namespace contractverify
         if (std::regex_match(type, match, regexArray))
                 return isTypeAllowedAsIO(match[1].str(), analysisData);
 
+        // Another special case are oracle related types:
+        // - OI::*::OracleQuery
+        // - OracleNotificationInput<*>
+        std::regex regexOracleQuery("OI::(\\w+)::OracleQuery");
+        std::regex regexOracleNotificationInput("OracleNotificationInput<\\w+>");
```
Comment (philippwerner) [inline src/lib/check_names_and_types.cpp]: I think it is better to use `"OracleNotificationInput<OI::(\\w+)>"`. Otherwise, it may be possible to insert forbidden structs here, right?

File: src/lib/check_names_and_types.cpp [hunk 2]
```diff
@@ -83,18 +83,91 @@ namespace contractverify
...
+                        foundScopeResolutions.pop();
+                    }
+                }
+            }
+            else if (name[pos] == ',' && !openingPositions.empty())
+            {
+                // Update lastRelevantPos to position after the comma (skip whitespace)
+                lastRelevantPos = pos + 1;
+                // Skip any whitespace after comma
+                while (lastRelevantPos < name.length() && name[lastRelevantPos] == ' ')
```
Comment (philippwerner) [inline src/lib/check_names_and_types.cpp]: For skipping whitespaces, I recommend using `std::isspace()` https://en.cppreference.com/w/cpp/string/byte/isspace
What happens if there are whitespaces at other positions? Maybe you should add an extra else-if for skipping other whitespaces. With long names and code formatting including line limits, there may be even newlines, I guess. Ideally, please also add a test case for that.

File: src/lib/check_names_and_types.cpp [hunk 3]
```diff
@@ -130,8 +203,8 @@ namespace contractverify
         // Another special case are oracle related types:
         // - OI::*::OracleQuery
         // - OracleNotificationInput<*>
-        std::regex regexOracleQuery("OI::(\\w+)::OracleQuery");
-        std::regex regexOracleNotificationInput("OracleNotificationInput<\\w+>");
+        std::regex regexOracleQuery("OI::\\w+::OracleQuery");
```
Comment (philippwerner) [inline src/lib/check_names_and_types.cpp:221]: We don't have a test case for this yet, but please also allow OI::*::OracleReply.

File: src/lib/check_names_and_types.cpp [hunk 4]
```diff
@@ -130,8 +203,8 @@ namespace contractverify
...
+        std::regex regexOracleNotificationInput("OracleNotificationInput<(\\w+)(:\\:\\w+)*>");
```
Comment (philippwerner) [inline src/lib/check_names_and_types.cpp]: So far, only structs from the OI namespace make sense here as the template parameter.
I'm concerned if it may be possible to insert forbidden structs here, such as `HashMap` or `Collection`. Ideally, please add a testcase for that, making sure that the check triggers and forbids these.

**Review by philippwerner — COMMENTED** [review]
@Franziska-Mueller Awesome, thank you! Just three comments.

File: src/lib/check_names_and_types.cpp (hunk 2 above)
Comment (Franziska-Mueller) [reply src/lib/check_names_and_types.cpp]: ideally, all these whitespaces should already have been removed by the lexer and parser. but unfortunately the templated type parsing doesn't seem to be reliable. I think I need to add this as a general TODO for the contract-verify tool.

File: src/lib/check_names_and_types.cpp (hunk 4 above)
Comment (Franziska-Mueller) [reply src/lib/check_names_and_types.cpp]: I made it more restrictive to only match `OracleNotificationInput<OI::\\w+>`

File: src/lib/check_names_and_types.cpp (hunk 2 above)
Comment (Franziska-Mueller) [reply src/lib/check_names_and_types.cpp]: ok, I resorted to just removing all whitespace in the checks contained in check_names_and_types.cpp

**Review by philippwerner — APPROVED** [review]
Thank you! 👍
